# Generated by Django 5.2.7 on 2025-11-14 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contacts_phone_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='dep_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='dep_name',
        ),
        migrations.AddField(
            model_name='contacts',
            name='doc_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.doctors'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='doc_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.doctors'),
        ),
    ]
