# Generated by Django 5.2.7 on 2025-11-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_contacts_dep_name_remove_feedback_dep_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='rating',
        ),
    ]
