# Generated by Django 5.2.7 on 2025-11-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_data',
            new_name='booking_date',
        ),
    ]
